### ISSUE TITLE
Respect max_line_length = off

### ISSUE THREAD

**Issue by alexanderschnitzler** [a-r-m-i-n/editorconfig-cli#1]
Hi Armin,

according to the docs (https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors), `off` is a valid value for setting `max_line_length` which should result in no rules being applied regarding line lengths.

**EDIT**

Forgot to mention that using `off` currently leads to this exception:

```
In MaxLineLength.php line 24:
                                              
  is not a valid value for 'max_line_length'                                         
```

Thanks for this great tool.
Alex

**Comment by a-r-m-i-n** [comment]
Hi Alex, thanks for reporting! I'll check it. I also wanted to update the library I've used to parse the actual .editorconfig.

**Comment by alexanderschnitzler** [comment]
I am not sure that the library is doing it wrong because when I look up its code, it looks like it respects the value `off`.

https://github.com/idiosyncratic-code/editorconfig-php/blob/main/src/Declaration/MaxLineLength.php#L22

Do you maybe check for integers only in your project?

Have a nice day.

**Comment by a-r-m-i-n** [comment]
It's probably type hinting related. My rule expects an int here. Should not be that hard to fix.

I'm going to work on it today :)

**Comment by a-r-m-i-n** [comment]
Upgrading the library did the trick :)
My CLI tool is not checking this attribute at all, currently. Missing feature?

**Comment by a-r-m-i-n** [comment]
@alexanderschnitzler Checkout latest master branch. There I've added the new feature 52f69572835af02ee898333d115e4fdb946a61df 😎
