### ISSUE TITLE
Version 1.2.0 removes all line feeds (LF)

### ISSUE THREAD

**Issue by alexanderschnitzler** [a-r-m-i-n/editorconfig-cli#2]
Hi Armin,

I just used version 1.2.0 on my code base with this config:

```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
charset = utf-8
end_of_line = LF
insert_final_newline = true
trim_trailing_whitespace = true

[*.php]
indent_style = space
indent_size = 4
```

After "fixing" my code base, all line feeds are removed, i.e. all files only contain 1 line afterwards. Example:

```php
<?php

declare(strict_types=1);

namespace App\Controller;

...
```

is squashed into one line like this:

```php
<?phpdeclare(strict_types=1);namespace App\Controller;...
```

Any idea what might be the issue?

Have a nice day,
Alex

**Comment by a-r-m-i-n** [comment]
Hi. I think the uppercase LF is the problem here, which I don't respect in LineEndingUtility. I'm going to fix it tomorrow.
