### ISSUE TITLE
Feature Request: Use config file with symfony/finder to define scanned directories

### ISSUE THREAD

**Issue by alexanderschnitzler** [a-r-m-i-n/editorconfig-cli#3]
It would be great if there was a config file like with **php-cs-fixer** where the scanned directories can be defined with an instance of `symfony/finder`.

**Comment by a-r-m-i-n** [comment]
Funny. A colleague and me got the same idea yesterday.

But I'm not sure if this is a good idea, because you could define exclusions with .editorconfig itself. Similar like using several .gitignore files within a project.

I'm not sure if editorconfig selectors also support directories. If it does you could also define all excludes in root editorconfig file.

With this in mind, do you still think we need a configurable Finder instance?

**Comment by a-r-m-i-n** [comment]
Oh. I've got another idea: How about evaluating existing gitignore files and auto exclude those files from scanning.

**Comment by alexanderschnitzler** [comment]
> I'm not sure if editorconfig selectors also support directories. If it does you could also define all excludes in root editorconfig file.

I don't really know that either. But I think that people would still benefit from being able to use a finder. Not only to define directories but also to define which files your tool should operate on.

> Oh. I've got another idea: How about evaluating existing gitignore files and auto exclude those files from scanning?

I like this idea. `syfmony/finder` can help with that out of the box btw: https://symfony.com/doc/current/components/finder.html#version-control-files

**Comment by a-r-m-i-n** [comment]
Oh sweet. I just knew ignoring vcs (.git) but ignoreVCSIgnored seems to do the trick here. 

And I think you are right. Providing the possibility to setup an own Finder instance, doesn't hurt.

But with the VCSignored flag set, I don't see valid use cases, except for testing purposes, currently.

**Comment by alexanderschnitzler** [comment]
What I usually do is to perform changes on files grouped by file types. I can of course just commit the changes to specific files but it's even easier to reduce the bulk edit by file type. Or let's say I have a huge code base and want smaller commits, I might commit files folder by folder (package by package).

Just had the case yesterday where everything was squashed into one commit and then something went wrong and we had to check the whole commit which was simply too big. A custom finder config helps performing changes on smaller parts only. The one doing git bisect will love this decision. :)

**Comment by a-r-m-i-n** [comment]
I've started to implemented it. Just docs are missing :)
